"""Shared metadata for the 16 Accounts tutorials (video + docx)."""

ADMIN = [("Accounts / Finance / CE", "admin", "admin")]

# key: (no, short_name, title, summary, outcome, leads)
ACC = [
    ("acc01_chart", 1, "Chart_of_Accounts", "Chart of Accounts",
     "Every account MCB uses to record money, how the codes are organised, and how to add one.",
     "You can find any account and create a new one correctly",
     "Flow 2 — journals decide which book each entry goes into."),
    ("acc02_journals", 2, "Journals", "Journals & Voucher Numbering",
     "Bank, Cash, Purchases, Sales and Miscellaneous — and how MCB's per-year voucher numbers work.",
     "Journals configured with MCB's July–June voucher numbering",
     "Flow 3 — the fiscal year and the tax rates."),
    ("acc03_fiscal_tax", 3, "Fiscal_Year_and_Tax", "Fiscal Year, VAT & TDS Setup",
     "Setting the July–June financial year and the VAT / TDS rates that MCB deducts.",
     "Fiscal year set to Jul–Jun · VAT and 5 TDS rates ready",
     "Flow 4 — the vendors and donors those taxes apply to."),
    ("acc04_partners", 4, "Vendors_and_Donors", "Vendors & Donors (BIN / TIN)",
     "Recording the tax registration numbers MCB needs on every challan and return.",
     "Vendors and donors carry their BIN and TIN",
     "Flow 5 — setup is done; now the daily vouchers."),
    ("acc05_voucher", 5, "Journal_Voucher", "Journal Voucher + 4-Level Approval",
     "Writing a journal voucher and taking it through Prepared → Checked → Reviewed → Approved.",
     "A posted voucher with all four approvals recorded",
     "Flow 6 — money coming in from donors."),
    ("acc06_receipt", 6, "Receipt_Voucher", "Receipt Voucher & Money Receipt",
     "Recording money received from a donor and printing the Annexure-01/31 money receipt.",
     "Donor receipt recorded and money receipt printed",
     "Flow 7 — money going out to vendors."),
    ("acc07_payment", 7, "Payment_Voucher", "Payment Voucher, Cheque & Checklist",
     "Paying a vendor by cheque, recording the cheque number, and signing the Annexure-28 checklist.",
     "Cheque payment recorded · checklist signed off",
     "Flow 8 — paying against a supplier bill and purchase order."),
    ("acc08_bill", 8, "Vendor_Bill", "Vendor Bill & 3-Way Match",
     "A bill raised from a purchase order, checked against the goods received before it can be paid.",
     "Bill matched (PO + GRN + Bill) and released for payment",
     "Flow 9 — the tax deducted at the moment of payment."),
    ("acc09_vat_tds", 9, "VAT_and_TDS", "VAT / TDS Challans & Monthly Summary",
     "Recording the treasury challan and producing the monthly Deductible / Deducted / Deposited / Dues summary.",
     "Challans recorded · monthly VAT-TDS position known",
     "Flow 10 — money advanced to staff."),
    ("acc10_advance", 10, "Advances", "Cash Advance & Adjustment",
     "Advancing money to staff for an activity (Annexure-18) and settling it afterwards (Annexure-19).",
     "Advance paid, then cleared with the real expenditure",
     "Flow 11 — small urgent cash and the petty cash box."),
    ("acc11_petty", 11, "IOU_and_Petty_Cash", "IOU & Petty Cash",
     "The lighter IOU route, topping up the cash box, counting it, and the petty cash book.",
     "Petty cash topped up, counted and reconciled",
     "Flow 12 — the budgets all this spending is measured against."),
    ("acc12_budget", 12, "Budgets", "Project Budget & Working Budget",
     "The annual project budget (Annexure-27) and the quarter-by-quarter working budget (Annexure-26).",
     "Budget in place with live consumption showing",
     "Flow 13 — changing a budget and reporting to the donor."),
    ("acc13_revision", 13, "Budget_Revision", "Budget Revision & Donor Report",
     "Moving money between budget lines — over 10% only the CE can approve — and the donor budget-vs-actual report.",
     "Revision approved by the right person · donor report produced",
     "Flow 14 — the things MCB owns."),
    ("acc14_assets", 14, "Fixed_Assets", "Fixed Assets: Register, Inventory & Disposal",
     "Assets with custodian, location and donor; the Annexure-07 register, physical inventory, and CE-gated disposal.",
     "Assets tracked, counted, and disposal properly controlled",
     "Flow 15 — agreeing the bank."),
    ("acc15_bank", 15, "Bank_Reconciliation", "Bank Reconciliation & Cheque Register",
     "Comparing the cash book against the bank statement (Annexure-17) and listing every cheque issued (Annexure-02).",
     "Bank agreed · every cheque accounted for",
     "Flow 16 — reading the numbers back out."),
    ("acc16_reports", 16, "Financial_Reports", "Financial Reports & Year-End Closing",
     "Balance Sheet, Profit & Loss, Trial Balance, General Ledger, Aged Receivable/Payable, the donor report, and the year-end close.",
     "Every report MCB and its auditors need, plus the year closed",
     "— the accounting cycle is complete."),
]

META = {k: (no, title, summary, ADMIN) for k, no, _s, title, summary, _o, _l in ACC}
END = {k: (outcome, leads) for k, _n, _s, _t, _sm, outcome, leads in ACC}
SHORT = {k: short for k, _n, short, _t, _s, _o, _l in ACC}
